# Generated by Django 5.0.4 on 2025-02-20 12:51

from django.db import migrations
from django.db.models import F, Case, When, Value


def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    PersonModel.objects.update(
        age_group=Case(
            When(age__lte=12, then=Value('Child')),
            When(age__range=(13, 17), then=Value('Teen')),
            When(age__gte=18, then=Value('Adult')),
            default=Value('No age group')
        )
    )

def set_age_group_default(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')
    PersonModel.objects.update(age_group=Value('No age group'))

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default),
    ]
