# Generated by Django 5.0.4 on 2025-02-20 13:41

from django.db import migrations
from django.db.models import F, Case, When, Value


def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')

    ItemModel.objects.update(
        rarity=Case(
            When(price__lte=10, then=Value('Rare')),
            When(price__lte=20, then=Value('Very Rare')),
            When(price__lte=30, then=Value('Extremely Rare')),
            When(price__gte=31, then=Value('Mega Rare')),
        )
    )

def reset_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')
    ItemModel.objects.update(rarity=Value('No rarity'))

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity, reverse_code=reset_rarity),
    ]
