# Generated by Django 5.0.4 on 2025-02-20 14:11

from django.db import migrations
from django.db.models import F, Case, When, Value
from django.db.models.functions import Length

MULTIPLIER = 120
EXPENSIVE_THRESHOLD = 750

def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.annotate(
        brand_length=Length('brand')
    ).update(price=F('brand_length') * MULTIPLIER)

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.update(
        category=Case(
            When(price__gte=EXPENSIVE_THRESHOLD, then=Value("Expensive")),
            When(price__lt=EXPENSIVE_THRESHOLD, then=Value("Cheap")),
        )
    )

def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_price = SmartphoneModel._meta.get_field("price").default
    SmartphoneModel.objects.update(price=default_price)

def reset_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_category = SmartphoneModel._meta.get_field("category").default
    SmartphoneModel.objects.update(category=default_category)

def reset_category_and_price(apps, schema_editor):
    reset_category(apps, schema_editor)
    reset_price(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_category_and_price, reverse_code=reset_category_and_price),
    ]
