# Generated by Django 5.0.4 on 2025-02-20 19:11
from datetime import timedelta

from django.db import migrations
from django.db.models import F


def update_delivery_and_warranty(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    OrderModel.objects.filter(status='P').update(delivery=F('order_date') + timedelta(days=3))
    OrderModel.objects.filter(status='C').update(warranty='24 months')
    OrderModel.objects.filter(status='CN').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(update_delivery_and_warranty),
    ]
